version: '3'
services:
  phoenix:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: phoenix
    expose:
      - ${PORT}
    restart: always
    volumes:
      - ./data:/app
    env_file:
      - .env
    environment:
      LETSENCRYPT_HOST:  ${DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_HOST:      ${DOMAIN}
      VIRTUAL_PORT:      ${PORT}
      TITLE:             ${TITLE}
      DOMAIN:            ${DOMAIN}
      APP_NAME:          ${APP_NAME}
      DB_USER:           ${DB_USER}
      DB_PASS:           ${DB_PASS}
      DB_NAME:           ${DB_NAME}
      DB_PORT:           ${DB_PORT}
      DB_HOST:           ${DB_HOST}
      PGUSER:            ${DB_USER}
      PGPASSWORD:        ${DB_PASS}
      PGDATABASE:        ${DB_NAME}
      PGPORT:            ${DB_PORT}
      PGHOST:            ${DB_HOST}
      MIX_ENV:           ${MIX_ENV}
    networks:
      - default
networks:
  default:
    external:
      name: nginx-proxy
