version: '3'
services:
  phoenix:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: phoenix
    expose:
      - 4000
    restart: always
    volumes:
      - ./data:/app
    env_file:
      - .env
    environment:
      LETSENCRYPT_HOST:  ${DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_HOST:      ${DOMAIN}
      VIRTUAL_PORT:      4000
      DB_USER:           ${DB_USER}
      DB_PASS:           ${DB_PASS}
      DB_NAME:           ${DB_NAME}
      DB_PORT:           ${DB_PORT}
      DB_HOST:           ${DB_HOST}
      DATABASE_URL:      ecto://${DB_USER}:${DB_PASS}@${DB_HOST}${DB_PORT}/${DB_NAME}
      PGUSER:            ${DB_USER}
      PGPASSWORD:        ${DB_PASS}
      PGDATABASE:        ${DB_NAME}
      PGPORT:            ${DB_PORT}
      PGHOST:            ${DB_HOST}
    networks:
      - default
networks:
  backend:
    driver: bridge
  default:
    external:
      name: nginx-proxy
